apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: IMAGE_PLACEHOLDER

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              valueFrom:
              secretKeyRef:
              name: backend-secret
              key: PORT
            - name: BASE_URL
              valueFrom:
              secretKeyRef:
              name: backend-secret-url
              key: BASE_URL
            - name: S3_BUCKET_NAME
              valueFrom:
              secretKeyRef:
              name: backend-secret-bucket
              key: S3_BUCKET_NAME
            - name: MODEL_ID
              valueFrom:
              secretKeyRef:
              name: backend-secret-model
              key: MODEL_ID